$schema: "https://json-schema.org/draft/2020-12/schema"
description: Configuration schema for xOPR workflow

properties:
  opr:
    type: object
    properties:
      cache_dir:
        type: string
        description: Directory for caching OPR data
      stac_api_url:
        type: ["string", "null"]
        description: STAC API URL (null for default)
    required: ["cache_dir"]
  
  region:
    type: object
    properties:
      name:
        type: ["string", "array"]
        description: Region name(s) from MEaSUREs dataset
      type:
        type: ["string", "null"]
        enum: ["GR", "FL", "IS", null]
        description: Region type
      regions:
        type: ["string", "array", "null"]
        description: Geographic regions (Peninsula, West, East)
    required: ["name"]
  
  search:
    type: object
    properties:
      max_items:
        type: ["integer", "null"]
        description: Maximum number of frames to process
    
  processing:
    type: object
    properties:
      data_product:
        type: string
        description: Data product to load
      resample_interval:
        type: string
        description: Temporal resampling interval
      layer_margin_m:
        type: number
        description: Margin around layers in meters
    required: ["data_product", "resample_interval", "layer_margin_m"]
  
  output:
    type: object
    properties:
      format:
        type: string
        enum: ["netcdf", "zarr"]
        description: Output format
      merge_frames:
        type: boolean
        description: Whether to merge frames
    required: ["format", "merge_frames"]
  
  visualization:
    type: object
    properties:
      create_maps:
        type: boolean
        description: Create interactive maps
      create_plots:
        type: boolean
        description: Create static plots
      projection:
        type: string
        description: Map projection EPSG code
    required: ["create_maps", "create_plots", "projection"]

required:
  - opr
  - region
  - search
  - processing
  - output
  - visualization
