# xOPR radar data processing workflow configuration

# OPR connection settings
opr:
  cache_dir: null

# Region selection parameters (using MEaSUREs Antarctic dataset)
region:
  name: "Dotson"  # Region name(s) - can be string or list
  type: "FL"      # Type: GR (grounded), FL (floating), IS (island), or null for all
  regions: null   # Regions: Peninsula, West, East, or null for all

# Frame search parameters
search:
  max_items: null  # Maximum frames to process (null for all)

# Processing parameters
processing:
  data_product: "CSARP_standard"  # Data product to load
  resample_interval: "5s"  # Temporal resampling interval
  layer_margin_m: 50  # Margin around layers for peak detection (meters)
  create_debug_plots: true  # Create debug plots showing surface/bed power for each frame

# Attenuation and basal properties estimation
attenuation:
  ice_permittivity: 3.17  # Relative dielectric permittivity of ice
  min_window_size_km: 20  # Minimum spatial window size for attenuation estimation
  max_window_size_km: 300  # Maximum spatial window size
  window_step_km: 5  # Window size increment
  alpha_range_db_km: [1, 50]  # Range of attenuation rates to test (dB/km)
  alpha_step_db_km: 0.5  # Attenuation rate step size
  correlation_threshold: 0.01  # Convergence criterion for decorrelation

# Output settings
output:
  format: "netcdf"  # Output format: netcdf or zarr

# Visualization settings
visualization:
  create_maps: true  # Create interactive maps
  create_plots: true  # Create static plots
  projection: "EPSG:3031"  # Map projection for Antarctic (EPSG:3031) or Greenland (EPSG:3413)
