name: Build and Deploy Results

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: snakemake
          use-mamba: true

      - name: Install Snakemake
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge -c bioconda snakemake snakemake-minimal -y

      - name: Run Snakemake workflow
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: >-
            --cores 2
            --use-conda
            --conda-frontend mamba
            --show-failed-logs
            --printshellcmds
            --verbose

      - name: Create index.html for GitHub Pages
        shell: bash
        run: |
          cat > results/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>xOPR Workflow Results</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  h1 {
                      color: #333;
                      border-bottom: 3px solid #4CAF50;
                      padding-bottom: 10px;
                  }
                  h2 {
                      color: #555;
                      margin-top: 30px;
                  }
                  .card {
                      background: white;
                      border-radius: 8px;
                      padding: 20px;
                      margin: 20px 0;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .card a {
                      color: #2196F3;
                      text-decoration: none;
                      font-weight: 500;
                  }
                  .card a:hover {
                      text-decoration: underline;
                  }
                  ul {
                      list-style-type: none;
                      padding: 0;
                  }
                  li {
                      padding: 8px 0;
                      border-bottom: 1px solid #eee;
                  }
                  li:last-child {
                      border-bottom: none;
                  }
                  .visualization-link {
                      display: inline-block;
                      padding: 12px 24px;
                      background: #4CAF50;
                      color: white !important;
                      border-radius: 4px;
                      margin: 10px 10px 10px 0;
                      text-decoration: none !important;
                  }
                  .visualization-link:hover {
                      background: #45a049;
                  }
              </style>
          </head>
          <body>
              <h1>🛰️ xOPR Ice Penetrating Radar Analysis Results</h1>

              <div class="card">
                  <h2>Interactive Visualizations</h2>
                  <a href="visualizations/frame_map.html" class="visualization-link">📍 Frame Coverage Map</a>
                  <a href="visualizations/results_map.html" class="visualization-link">📊 Results Map</a>
              </div>

              <div class="card">
                  <h2>Region Data</h2>
                  <ul>
                      <li>📄 <a href="region/selected_region.geojson">Selected Region (GeoJSON)</a></li>
                  </ul>
              </div>

              <div class="card">
                  <h2>Search Results</h2>
                  <ul>
                      <li>📄 <a href="search/frame_items.parquet">Frame Items (Parquet)</a></li>
                  </ul>
              </div>

              <div class="card">
                  <h2>Processed Data</h2>
                  <ul>
                      <li>📄 <a href="processed_frames/merged_frames.nc">Merged Frames (NetCDF)</a></li>
                  </ul>
              </div>

              <div class="card">
                  <p><em>Generated by xOPR Snakemake workflow</em></p>
                  <p>Source: <a href="https://github.com/thomasteisberg/xopr-snakemake-demo">GitHub Repository</a></p>
              </div>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
